<?php

require "inc/processing.inc";

$title = "3v Glossary";
writeTop($title, $title, '');

echo "<div class='threev-content'>\n";
echo "  <div class='threev-section'>\n";
echo "    <h2>Glossary</h2>\n";
echo "    <p>This page defines the volume terms used by 3v. The probe radius determines which surface is measured; larger probes smooth away small pockets, smaller probes follow fine detail.</p>\n";
echo "  </div>\n";

echo "  <div class='threev-section'>\n";
echo "    <h2>External volumes</h2>\n";
echo "    <div class='threev-grid'>\n";
echo "      <figure>\n";
echo "        <a href='img/lysozyme-00.0.mrc.2.png'><img width='128' height='128' src='img/lysozyme-00.0.mrc.2.png' alt='Probe 0.0'></a>\n";
echo "        <figcaption>Probe 0.0 &Aring; (VDW)</figcaption>\n";
echo "      </figure>\n";
echo "      <figure>\n";
echo "        <a href='img/lysozyme-01.0.mrc.2.png'><img width='128' height='128' src='img/lysozyme-01.0.mrc.2.png' alt='Probe 1.0'></a>\n";
echo "        <figcaption>Probe 1.0 &Aring;</figcaption>\n";
echo "      </figure>\n";
echo "      <figure>\n";
echo "        <a href='img/lysozyme-02.0.mrc.2.png'><img width='128' height='128' src='img/lysozyme-02.0.mrc.2.png' alt='Probe 2.0'></a>\n";
echo "        <figcaption>Probe 2.0 &Aring;</figcaption>\n";
echo "      </figure>\n";
echo "      <figure>\n";
echo "        <a href='img/lysozyme-04.0.mrc.2.png'><img width='128' height='128' src='img/lysozyme-04.0.mrc.2.png' alt='Probe 4.0'></a>\n";
echo "        <figcaption>Probe 4.0 &Aring;</figcaption>\n";
echo "      </figure>\n";
echo "      <figure>\n";
echo "        <a href='img/lysozyme-08.0.mrc.2.png'><img width='128' height='128' src='img/lysozyme-08.0.mrc.2.png' alt='Probe 8.0'></a>\n";
echo "        <figcaption>Probe 8.0 &Aring;</figcaption>\n";
echo "      </figure>\n";
echo "    </div>\n";
echo "    <dl class='threev-defs'>\n";
echo "      <dt>Van der Waals (VDW) volume</dt>\n";
echo "      <dd>The volume defined by the union of all atomic spheres at their van der Waals radii.</dd>\n";
echo "      <dt>Solvent-accessible volume</dt>\n";
echo "      <dd>The volume defined by expanding each atom by the solvent probe radius (typically 1.5 &Aring;) and taking the union of those expanded spheres.</dd>\n";
echo "      <dt>Solvent-excluded volume</dt>\n";
echo "      <dd>The volume inside the surface traced by a rolling solvent probe; it excludes regions the probe center cannot reach.</dd>\n";
echo "      <dt>ASA/SAS/SES context (from Wikipedia)</dt>\n";
echo "      <dd>The solvent-accessible surface area (ASA/SAS) is traced by the center of a rolling probe, while the solvent-excluded surface (SES, also called the Connolly surface) follows the probe’s outer envelope around atoms. The SES concept is closely related to ASA and uses rolling-ball methods originally developed by Richards and later implemented in 3D by Connolly and Richmond.</dd>\n";
echo "      <dd><strong>References cited on Wikipedia:</strong>\n";
echo "        <ul>\n";
echo "          <li>Richards, F.M. (1977). Areas, volumes, packing and protein structure. <em>Annu Rev Biophys Bioeng</em>. doi:10.1146/annurev.bb.06.060177.001055</li>\n";
echo "          <li>Connolly, M.L. (1983). Analytical molecular surface calculation. <em>J Appl Crystallogr</em>. doi:10.1107/S0021889883010985</li>\n";
echo "          <li>Richmond, T.J. (1984). Solvent accessible surface area and excluded volume in proteins. <em>J Mol Biol</em>. doi:10.1016/0022-2836(84)90231-6</li>\n";
echo "          <li>Connolly, M.L. (1993). The molecular surface package. <em>J Mol Graphics</em>. doi:10.1016/0263-7855(93)87010-3</li>\n";
echo "        </ul>\n";
echo "        <a href='https://en.wikipedia.org/wiki/Accessible_surface_area'>Wikipedia: Accessible surface area</a>\n";
echo "      </dd>\n";
echo "      <dt>Shell volume</dt>\n";
echo "      <dd>The limiting surface used to separate inside from outside. It is the boundary that 3v uses to define “interior.”</dd>\n";
echo "      <dt>Convex hull volume</dt>\n";
echo "      <dd>The smallest convex volume that fully encloses the structure. Conceptually equivalent to an infinite-radius probe.</dd>\n";
echo "    </dl>\n";
echo "  </div>\n";

echo "  <div class='threev-section'>\n";
echo "    <h2>Internal volumes</h2>\n";
echo "    <div class='threev-grid'>\n";
echo "      <figure>\n";
echo "        <a href='img/lysozyme_layers.png'><img width='245' height='260' src='img/lysozyme_layers.png' alt='Lysozyme layers'></a>\n";
echo "        <figcaption>Lysozyme cross-section</figcaption>\n";
echo "      </figure>\n";
echo "      <figure>\n";
echo "        <a href='img/ribosome_layers.png'><img width='240' height='306' src='img/ribosome_layers.png' alt='Ribosome layers'></a>\n";
echo "        <figcaption>50S ribosome cross-section</figcaption>\n";
echo "      </figure>\n";
echo "    </div>\n";
echo "    <div class='threev-note'>\n";
echo "      <strong>Legend:</strong> Inside the VDW surface (dark blue) and solvent-excluded surface (light blue), cavities are light green and channels are light red. The outer boundary is the shell surface.\n";
echo "    </div>\n";
echo "    <dl class='threev-defs'>\n";
echo "      <dt>Empty volume</dt>\n";
echo "      <dd>Solvent-excluded volume minus VDW volume. These are tiny voids between atoms that a solvent probe cannot access.</dd>\n";
echo "      <dt>Solvent volume</dt>\n";
echo "      <dd>Shell volume minus solvent-excluded volume. This includes all probe-accessible interior space.</dd>\n";
echo "      <dt>Cavity volume</dt>\n";
echo "      <dd>Interior solvent volume that is enclosed and not connected to the exterior by a probe-accessible path.</dd>\n";
echo "      <dt>Channel volume</dt>\n";
echo "      <dd>Interior solvent volume that is connected to the exterior (solvent volume minus cavity volume).</dd>\n";
echo "    </dl>\n";
echo "  </div>\n";

echo "  <div class='threev-section'>\n";
echo "    <h2>Parameter quick reference</h2>\n";
echo "    <ul>\n";
echo "      <li><strong>Probe radius</strong>: Larger probes smooth away small pockets; smaller probes capture finer details.</li>\n";
echo "      <li><strong>Grid resolution</strong>: Higher resolution uses smaller voxels (more detail, slower).</li>\n";
echo "      <li><strong>Shell method</strong>: Determines how the limiting surface is computed for cavity/channel separation.</li>\n";
echo "    </ul>\n";
echo "  </div>\n";

echo "  <div class='threev-section'>\n";
echo "    <h2>Program summaries</h2>\n";
echo "    <div class='threev-grid'>\n";
echo "      <figure>\n";
echo "        <img src='img/richards.png' width='220' alt='Rolling probe'>\n";
echo "        <figcaption><strong>Volume Assessor</strong></figcaption>\n";
echo "      </figure>\n";
echo "      <div>\n";
echo "        <p><strong>Volume Assessor</strong> calculates the volume of your macromolecule of interest. A virtual probe rolls over the molecular surface and the volume is computed from the resulting envelope.</p>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "    <hr/>\n";
echo "    <div class='threev-grid'>\n";
echo "      <figure>\n";
echo "        <img src='img/solvent.png' width='320' alt='Solvent and channel volumes'>\n";
echo "        <figcaption><strong>Channel Finder</strong></figcaption>\n";
echo "      </figure>\n";
echo "      <div>\n";
echo "        <p><strong>Channel Finder</strong> is one of the most useful tools. It can pull interesting channels out from a structure (for example, the ribosome exit tunnel or the internal cavity of GroEL).</p>\n";
echo "        <p>Channel Finder works by calculating the shell volume (A), subtracting the solvent-excluded volume (B) to get the solvent volume (C), then retaining only the solvent volume connected to a user-specified point.</p>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "    <hr/>\n";
echo "    <div class='threev-grid'>\n";
echo "      <figure>\n";
echo "        <a href='img/grid_vs_probe.jpg'><img src='img/grid_vs_probe_sm.jpg' width='260' alt='Grid size vs probe size'></a>\n";
echo "        <figcaption><strong>Simple 3D Printer Prep</strong></figcaption>\n";
echo "      </figure>\n";
echo "      <div>\n";
echo "        <p><strong>Simple 3D Printer Prep</strong> calculates the volume of your macromolecule of interest using the same rolling-probe approach as Volume Assessor, then prepares a simplified mesh suitable for printing.</p>\n";
echo "        <p>The figure highlights the difference between grid resolution and probe size.</p>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "  </div>\n";

echo "  <div class='threev-section'>\n";
echo "    <h2>Guided tutorials (quick exercises)</h2>\n";
echo "    <p>Use the preset buttons on each tool page to run a known example. These are designed as short, repeatable exercises you can share with students or new lab members.</p>\n";
echo "    <ol>\n";
echo "      <li><strong>Volume Assessor (Lysozyme):</strong> On the Volume page, run <em>Lysozyme - Solvent Excluded</em> and <em>Lysozyme - Shell</em>. Compare how the probe radius changes the overall envelope.</li>\n";
echo "      <li><strong>Channel Finder (Ribosome exit tunnel):</strong> On Channel Finder, run <em>50S Ribosomal Subunit</em>. Inspect the resulting channel and compare it to known exit tunnel geometry.</li>\n";
echo "      <li><strong>Channel Finder (GroEL cavity):</strong> Try the <em>GroEL cavity</em> preset and compare channel connectivity to the solvent-excluded surface.</li>\n";
echo "      <li><strong>3D Print Prep:</strong> On Simple 3D Printer Prep, run the lysozyme preset and compare grid resolution versus probe size in the output meshes.</li>\n";
echo "    </ol>\n";
echo "  </div>\n";

echo "  <div class='threev-section'>\n";
echo "    <h2>Parameter intuition</h2>\n";
echo "    <ul>\n";
echo "      <li><strong>Probe radius:</strong> Small probes capture narrow crevices; large probes smooth them away. If a channel disappears, increase the probe size or switch to Channel Finder with an anchor point.</li>\n";
echo "      <li><strong>Grid resolution:</strong> Finer grids increase detail but slow down runs. Use coarse grids for exploration, then rerun with higher resolution for publication figures.</li>\n";
echo "      <li><strong>Channel anchor point:</strong> The specified point should lie inside the target channel or cavity. If the result is empty, try a nearby point or a larger small-probe radius.</li>\n";
echo "      <li><strong>Shell method:</strong> The shell surface defines interior vs exterior. If cavities look fragmented, try a larger probe or a different shell method.</li>\n";
echo "    </ul>\n";
echo "  </div>\n";

echo "  <div class='threev-section'>\n";
echo "    <h2>Interpreting results</h2>\n";
echo "    <ul>\n";
echo "      <li><strong>Channels vs cavities:</strong> Channels connect to the exterior; cavities are enclosed. Use the Channel Finder or Cavity Extract tools to separate them.</li>\n";
echo "      <li><strong>Binary volumes:</strong> Many outputs are binary (0/1). Use low thresholds (around 0.01) in ChimeraX/Chimera to render clean surfaces.</li>\n";
echo "      <li><strong>Compare across probes:</strong> A probe series (Volume Range) can reveal whether a pocket is robust or probe-size sensitive.</li>\n";
echo "    </ul>\n";
echo "  </div>\n";

echo "  <div class='threev-section'>\n";
echo "    <h2>Common pitfalls</h2>\n";
echo "    <ul>\n";
echo "      <li><strong>Empty output:</strong> Usually a probe or anchor-point issue. Try a smaller probe or move the anchor point into the channel.</li>\n";
echo "      <li><strong>Over-smoothing:</strong> If fine features vanish, reduce probe radius or increase grid resolution.</li>\n";
echo "      <li><strong>Performance:</strong> Large structures at high resolution can take time. Start coarse, then refine.</li>\n";
echo "    </ul>\n";
echo "  </div>\n";
echo "</div>\n";

writeBottom();
exit;

?>
