<?php

require "inc/processing.inc";

$title = "3v Volume Viewing Guide";
writeTop($title,$title,'');

echo "<table border='0' cellpading='3'><tr><td align='left'>\n";

/*********************************/
/*********************************/
echo "<br/>";
echo "<h1>Volume Viewing Guide</h1>";
echo "<hr/>";
echo "</td></tr><tr><td align='left'>\n";

/*********************************/
/*********************************/
echo "<h2>UCSF Chimera Tutorial</h2>";
echo "
<h3>UCSF Chimera website provides a nice tutorial on using its program:</h3>

<ul>
<li>
<a href='http://www.cgl.ucsf.edu/chimera/tutorials/groel/groel.html'>
GroEL Density map and PDB model display tutorial.
</a></li>
</ul>

<br/>

<h3>To view volume from the 3v website:</h3>

<ul>
<li>Download the gzipped MRC files
<li>Download the gzipped PDB file
<li>Unzip the MRC file, Chimera can read zipped PDB files, but not zipped MRC files
<li>Open the files in Chimera
<li>The a large window with the structure and the Volume Viewer window will appear
</ul>

<img src='img/volumeviewer1.png' width='428' height='276'>

<ul>
<li>The MRC files generated by 3v are binary (values of 0 and 1)
<li>The best threshold for 3v files seems to be 0.01
<li>It is also a good idea to give the volume some color by clicking on the gray box
<li>By selecting 'Surface and Mesh Options' from the Features menu you can add surface smoothing
</ul>

<img src='img/volumeviewer2.png' width='428' height='562'>

<ul>
<li>With a little bit of playing you get an image like this
</ul>

<img src='img/pgp-struct.png' width='612' height='442'>

";


/*********************************/
echo "</td></tr></table>\n";

writeBottom();
exit;

?>


